import { glob } from "fs/promises"
import * as path from "path"
import * as fs from "fs"

const dist = path.resolve(import.meta.dirname, "../../app/dist")
const files: string[] = []
for await (const entry of glob("**/*", { cwd: dist })) {
  if (!entry.endsWith(".map")) files.push(entry.replaceAll("\\", "/"))
}
files.sort()

const dir = path.resolve(import.meta.dirname, "../src")
const imports = files.map((f, i) => {
  const rel = path.relative(dir, path.join(dist, f)).replaceAll("\\", "/")
  const spec = rel.startsWith(".") ? rel : "./" + rel
  return `import file_${i} from ${JSON.stringify(spec)} with { type: "file" };`
})
const entries = files.map((f, i) => `  ${JSON.stringify(f)}: file_${i},`)

const content = [
  "// Auto-generated by gen-web-ui.ts",
  ...imports,
  "",
  "const embeddedFileMap: Record<string, string> = {",
  ...entries,
  "}",
  "",
  "export default embeddedFileMap",
  "",
].join("\n")

fs.writeFileSync(path.join(dir, "opencode-web-ui.gen.ts"), content)
console.log(`Generated opencode-web-ui.gen.ts with ${files.length} files`)
